baseURL = "/" #'https://askeijaz.github.io/sifar.github.io/'
languageCode = 'en-us'
title = 'The Sifar Maverick Site'
theme = 'maverick'

[permalinks]
  pages = "/:slug"

[params]
  logo = '/assets/favicon.ico'
  description = "A minimal hugo theme focus on content"
  author = 'Eijaz Sheikh'
  items = 10

  [params.comments]
    enabled = true
    githubRepo = 'askeijaz/sifar'
    theme = 'github-light'


[menu]
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = "110"
  [[menu.main]]
    identifier = "posts"
    name = "Post"
    url = "/posts/"
    weight = 200
  [[menu.main]]
    identifier = "courses"
    name = "Courses"
    url = "/courses/"
    weight = 300
  [[menu.main]]
    identifier = "series"
    name = "Series"
    url = "/series/"
    weight = 400
  [[menu.main]]
    identifier = "speaking"
    name = "Speaking"
    url = "/speaking/"
    weight = 500

[markup]
  [markup.goldmark.renderer]
    unsafe = true
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'monokailight'
    tabWidth = 4

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
  section = ["HTML"]

[outputFormats.RSS]
  mediatype = "application/rss"
  baseName = "atom"

[outputFormats.JSON]
  mediatype = "application/json"
  baseName = "feed"

ignoreErrors = ["error-remote-getjson"]

[caches]
  [caches.images]
    dir = ':cacheDir/images'